"""SIMS Plus Models package."""

from app.models.base import Base, TenantMixin, SoftDeleteMixin, AuditMixin
from app.models.tenant import Tenant, TenantType, SubscriptionTier
from app.models.user import User, UserRole, UserStatus
from app.models.school import School, SchoolType, SchoolStatus
from app.models.reserved_subdomain import ReservedSubdomain, DEFAULT_RESERVED_SUBDOMAINS
from app.models.audit_log import AuditLog
from app.models.academic import (
    AcademicYear,
    AcademicYearStatus,
    Term,
    TermStatus,
    Class,
    ClassLevel,
    ClassSection,
    Subject,
    SubjectCategory,
    ClassSubject,
    GradingScale,
    GradingScaleType,
    Grade,
    AssessmentWeight,
    AcademicSettings,
    DayOfWeek,
    ClassTimetable,
    SchoolPeriod,
    SchoolHoliday,
)
from app.models.student import (
    Student,
    StudentStatus,
    Gender,
    Guardian,
    StudentGuardian,
    GuardianRelationship,
)
from app.models.staff import (
    Department,
    Staff,
    StaffType,
    StaffStatus,
    StaffClassAssignment,
)
from app.models.attendance import (
    AttendanceStatus,
    StudentAttendance,
    StaffAttendance,
)
from app.models.exam import (
    Exam,
    ExamType,
    ExamStatus,
    ExamSubject,
    ExamSubjectStatus,
    ExamScore,
    ContinuousAssessment,
    AssessmentType,
    TermReport,
)
from app.models.preschool import (
    LearningArea,
    DevelopmentalSkill,
    PreschoolRatingScale,
    PreschoolRating,
    StudentSkillAssessment,
    ProgressObservation,
    ObservationType,
    DailyActivityLog,
    MoodType,
    MealAmount,
    NapQuality,
    PreschoolReport,
)
from app.models.finance import (
    FeeStructure,
    FeeItem,
    FeeType,
    FeeTypeCategory,
    Invoice,
    InvoiceStatus,
    InvoiceItem,
    InvoiceScholarshipItem,
    Payment,
    PaymentMethod,
    PaymentStatus,
    Scholarship,
    ScholarshipType,
    CoverageType,
    StudentScholarship,
    ScholarshipStatus,
    ScholarshipApplication,
    ApplicationStatus,
    FinanceAuditLog,
    FinanceAuditAction,
    RenewalType,
    CreditNote,
    CreditNoteStatus,
    CreditNoteType,
    # Invoice status workflow validation
    INVOICE_STATUS_TRANSITIONS,
    is_valid_invoice_transition,
    get_valid_next_statuses,
)

__all__ = [
    "Base",
    "TenantMixin",
    "SoftDeleteMixin",
    "AuditMixin",
    "Tenant",
    "TenantType",
    "SubscriptionTier",
    "User",
    "UserRole",
    "UserStatus",
    "School",
    "SchoolType",
    "SchoolStatus",
    "ReservedSubdomain",
    "DEFAULT_RESERVED_SUBDOMAINS",
    "AuditLog",
    # Academic models
    "AcademicYear",
    "AcademicYearStatus",
    "Term",
    "TermStatus",
    "Class",
    "ClassLevel",
    "ClassSection",
    "Subject",
    "SubjectCategory",
    "ClassSubject",
    "GradingScale",
    "GradingScaleType",
    "Grade",
    "AssessmentWeight",
    "AcademicSettings",
    "DayOfWeek",
    "ClassTimetable",
    "SchoolPeriod",
    "SchoolHoliday",
    # Student models
    "Student",
    "StudentStatus",
    "Gender",
    "Guardian",
    "StudentGuardian",
    "GuardianRelationship",
    # Staff models
    "Department",
    "Staff",
    "StaffType",
    "StaffStatus",
    "StaffClassAssignment",
    # Attendance models
    "AttendanceStatus",
    "StudentAttendance",
    "StaffAttendance",
    # Exam models
    "Exam",
    "ExamType",
    "ExamStatus",
    "ExamSubject",
    "ExamSubjectStatus",
    "ExamScore",
    "ContinuousAssessment",
    "AssessmentType",
    "TermReport",
    # Preschool models
    "LearningArea",
    "DevelopmentalSkill",
    "PreschoolRatingScale",
    "PreschoolRating",
    "StudentSkillAssessment",
    "ProgressObservation",
    "ObservationType",
    "DailyActivityLog",
    "MoodType",
    "MealAmount",
    "NapQuality",
    "PreschoolReport",
    # Finance models
    "FeeStructure",
    "FeeItem",
    "FeeType",
    "FeeTypeCategory",
    "Invoice",
    "InvoiceStatus",
    "InvoiceItem",
    "InvoiceScholarshipItem",
    "Payment",
    "PaymentMethod",
    "PaymentStatus",
    "Scholarship",
    "ScholarshipType",
    "CoverageType",
    "StudentScholarship",
    "ScholarshipStatus",
    "ScholarshipApplication",
    "ApplicationStatus",
    "FinanceAuditLog",
    "FinanceAuditAction",
    "RenewalType",
    "CreditNote",
    "CreditNoteStatus",
    "CreditNoteType",
    # Invoice status workflow validation
    "INVOICE_STATUS_TRANSITIONS",
    "is_valid_invoice_transition",
    "get_valid_next_statuses",
]
