"""
SIMS Plus - Finance Report Endpoints

PDF report generation endpoints for fee collection, outstanding fees,
and payment summaries.
"""

from datetime import datetime
from io import BytesIO
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse

from app.api.deps import (
    DatabaseSession,
    RequestTenant,
    ValidatedUser,
    require_permissions,
)
from app.schemas.reports import FinancialReportRequest, FinancialReportType
from app.services.finance import FinanceReportService, FinanceReportError

import structlog

logger = structlog.get_logger()

router = APIRouter()


async def _generate_simple_pdf(
    title: str,
    headers: list[str],
    rows: list[list],
    summary: dict | None = None,
) -> bytes:
    """
    Generate a simple tabular PDF report using WeasyPrint.

    This is a lightweight helper for financial reports that don't yet
    have a dedicated branded template. Uses a clean table layout with
    SIMS Plus styling.
    """
    from weasyprint import HTML

    header_html = "".join(f"<th>{h}</th>" for h in headers)

    rows_html = ""
    for row in rows:
        cells = "".join(f"<td>{cell}</td>" for cell in row)
        rows_html += f"<tr>{cells}</tr>"

    summary_html = ""
    if summary:
        for key, value in summary.items():
            summary_html += f"<p><strong>{key}:</strong> {value}</p>"

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; color: #333; }}
            h1 {{ color: #1B4F72; border-bottom: 2px solid #1B4F72; padding-bottom: 10px; }}
            table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
            th {{ background-color: #1B4F72; color: white; padding: 10px; text-align: left; }}
            td {{ padding: 8px 10px; border-bottom: 1px solid #ddd; }}
            tr:nth-child(even) {{ background-color: #f9fafb; }}
            .summary {{ background-color: #f0f4f8; padding: 15px; border-radius: 8px; margin-top: 20px; }}
            .generated {{ color: #666; font-size: 12px; margin-top: 30px; }}
        </style>
    </head>
    <body>
        <h1>{title}</h1>
        <table>
            <thead><tr>{header_html}</tr></thead>
            <tbody>{rows_html}</tbody>
        </table>
        <div class="summary">{summary_html}</div>
        <p class="generated">Generated by SIMS Plus on {datetime.now().strftime("%d/%m/%Y %H:%M")}</p>
    </body>
    </html>
    """

    pdf_bytes = HTML(string=html_content).write_pdf()
    return pdf_bytes


# =========================
# Finance Report Endpoints
# =========================


@router.post(
    "/reports/fee-collection",
    summary="Generate fee collection report PDF",
    dependencies=[Depends(require_permissions("finance.reports"))],
    responses={200: {"content": {"application/pdf": {}}}},
)
async def generate_fee_collection_report(
    request: FinancialReportRequest,
    tenant: RequestTenant,
    user: ValidatedUser,
    db: DatabaseSession,
) -> StreamingResponse:
    """
    Generate a fee collection report as PDF.

    Shows payment totals broken down by fee type for the given academic year,
    term, class, and date range filters. Requires `finance.reports` permission.
    """
    service = FinanceReportService(db)

    try:
        data = await service.get_fee_collection_data(
            tenant_id=tenant.tenant_id,
            academic_year_id=request.academic_year_id,
            term_id=request.term_id,
            class_id=request.class_id,
            date_from=request.date_from,
            date_to=request.date_to,
        )
    except FinanceReportError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=e.message,
        )

    # Build table data from fee type breakdown
    headers = ["Fee Type", "Payments", "Total Collected"]
    rows = [
        [
            item["fee_type"],
            str(item["payment_count"]),
            f"{item['total_collected']:,.2f}",
        ]
        for item in data["fee_type_breakdown"]
    ]

    summary = {
        "Total Payments": str(data["total_payments"]),
        "Grand Total Collected": f"{data['grand_total']:,.2f}",
    }

    pdf_bytes = await _generate_simple_pdf(
        title="Fee Collection Report",
        headers=headers,
        rows=rows,
        summary=summary,
    )

    return StreamingResponse(
        BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": "attachment; filename=fee-collection-report.pdf",
        },
    )


@router.post(
    "/reports/outstanding-fees",
    summary="Generate outstanding fees report PDF",
    dependencies=[Depends(require_permissions("finance.reports"))],
    responses={200: {"content": {"application/pdf": {}}}},
)
async def generate_outstanding_fees_report(
    request: FinancialReportRequest,
    tenant: RequestTenant,
    user: ValidatedUser,
    db: DatabaseSession,
) -> StreamingResponse:
    """
    Generate an outstanding fees report as PDF.

    Lists students with unpaid invoice balances for the given academic year
    and optional term/class filters. Requires `finance.reports` permission.
    """
    service = FinanceReportService(db)

    try:
        data = await service.get_outstanding_fees_data(
            tenant_id=tenant.tenant_id,
            academic_year_id=request.academic_year_id,
            term_id=request.term_id,
            class_id=request.class_id,
        )
    except FinanceReportError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=e.message,
        )

    # Build table data from students with outstanding balances
    headers = ["Student ID", "Name", "Class", "Total Invoiced", "Total Paid", "Balance Due"]
    rows = [
        [
            s["student_number"] or "N/A",
            s["name"],
            s["class_name"],
            f"{s['total_invoiced']:,.2f}",
            f"{s['total_paid']:,.2f}",
            f"{s['balance_due']:,.2f}",
        ]
        for s in data["students"]
    ]

    summary = {
        "Total Students with Outstanding Balances": str(data["total_students"]),
        "Total Outstanding Amount": f"{data['total_outstanding']:,.2f}",
    }

    pdf_bytes = await _generate_simple_pdf(
        title="Outstanding Fees Report",
        headers=headers,
        rows=rows,
        summary=summary,
    )

    return StreamingResponse(
        BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": "attachment; filename=outstanding-fees-report.pdf",
        },
    )


@router.post(
    "/reports/payment-summary",
    summary="Generate payment summary report PDF",
    dependencies=[Depends(require_permissions("finance.reports"))],
    responses={200: {"content": {"application/pdf": {}}}},
)
async def generate_payment_summary_report(
    request: FinancialReportRequest,
    tenant: RequestTenant,
    user: ValidatedUser,
    db: DatabaseSession,
) -> StreamingResponse:
    """
    Generate a payment summary report as PDF.

    Shows payment totals broken down by payment method (cash, mobile money,
    bank transfer, etc.) for the given filters. Requires `finance.reports` permission.
    """
    service = FinanceReportService(db)

    try:
        data = await service.get_payment_summary_data(
            tenant_id=tenant.tenant_id,
            academic_year_id=request.academic_year_id,
            term_id=request.term_id,
            date_from=request.date_from,
            date_to=request.date_to,
        )
    except FinanceReportError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=e.message,
        )

    # Build table data from payment method breakdown
    headers = ["Payment Method", "Count", "Total Amount"]
    rows = [
        [
            m["payment_method"].replace("_", " ").title(),
            str(m["count"]),
            f"{m['total']:,.2f}",
        ]
        for m in data["method_breakdown"]
    ]

    summary = {
        "Total Payments": str(data["total_payments"]),
        "Grand Total": f"{data['grand_total']:,.2f}",
    }

    pdf_bytes = await _generate_simple_pdf(
        title="Payment Summary Report",
        headers=headers,
        rows=rows,
        summary=summary,
    )

    return StreamingResponse(
        BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": "attachment; filename=payment-summary-report.pdf",
        },
    )
