"""
SIMS Plus - Students Endpoints

API endpoints for student management.
"""

from typing import Optional
from uuid import UUID

from fastapi import APIRouter, Depends, File, Form, HTTPException, Query, UploadFile, status

from sqlalchemy import select

from app.api.deps import (
    CurrentUserId,
    DatabaseSession,
    RequestTenant,
    require_permissions,
)
from app.models.school import School
from app.schemas import PaginatedResponse
from app.schemas.student import (
    # Guardian
    GuardianCreate,
    GuardianUpdate,
    GuardianResponse,
    GuardianListResponse,
    # Student-Guardian
    StudentGuardianCreate,
    StudentGuardianWithNewGuardian,
    StudentGuardianUpdate,
    StudentGuardianResponse,
    # Student
    StudentCreate,
    StudentUpdate,
    StudentResponse,
    StudentWithGuardiansResponse,
    StudentListResponse,
    StudentBulkCreate,
    StudentBulkResponse,
    StudentStatsResponse,
    StudentImportResponse,
)
from app.services.student import StudentService, StudentServiceError

router = APIRouter()


# =========================
# Student Endpoints
# =========================


@router.post(
    "",
    response_model=StudentResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create student",
    dependencies=[Depends(require_permissions("students.create"))],
)
async def create_student(
    data: StudentCreate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentResponse:
    """Create a new student.

    Note: student_id is always auto-generated by the system.
    Use previous_student_id to store IDs from external/previous systems.
    """
    service = StudentService(db)

    max_retries = 5

    # Get school's student_id_prefix for auto-generation
    prefix = "STU"  # Default
    if data.school_id:
        school_result = await db.execute(
            select(School.student_id_prefix).where(School.id == data.school_id)
        )
        school_prefix = school_result.scalar_one_or_none()
        if school_prefix:
            prefix = school_prefix
    else:
        # Get first school for tenant
        school_result = await db.execute(
            select(School.student_id_prefix).where(School.tenant_id == tenant.tenant_id).limit(1)
        )
        school_prefix = school_result.scalar_one_or_none()
        if school_prefix:
            prefix = school_prefix

    # Convert guardians to dict format if provided
    guardians_data = None
    if data.guardians:
        guardians_data = [
            {
                "guardian": g.guardian.model_dump(),
                "relationship": g.relationship,
                "is_primary": g.is_primary,
                "is_emergency_contact": g.is_emergency_contact,
                "can_pickup": g.can_pickup,
            }
            for g in data.guardians
        ]

    # Retry loop for handling concurrent ID generation conflicts
    last_error = None
    for attempt in range(max_retries):
        try:
            # Always auto-generate student ID
            student_id = await service.generate_student_id(tenant.tenant_id, prefix)

            student = await service.create_student(
                tenant_id=tenant.tenant_id,
                student_id=student_id,
                previous_student_id=data.previous_student_id,
                first_name=data.first_name,
                middle_name=data.middle_name,
                last_name=data.last_name,
                date_of_birth=data.date_of_birth,
                gender=data.gender,
                email=data.email,
                phone=data.phone,
                address=data.address,
                city=data.city,
                region=data.region,
                ghana_card_number=data.ghana_card_number,
                nhis_number=data.nhis_number,
                school_id=data.school_id,
                class_id=data.class_id,
                section_id=data.section_id,
                admission_date=data.admission_date,
                admission_number=data.admission_number,
                status=data.status,
                is_boarder=data.is_boarder,
                blood_group=data.blood_group,
                medical_conditions=data.medical_conditions,
                allergies=data.allergies,
                photo_url=data.photo_url,
                notes=data.notes,
                guardians=guardians_data,
            )
            return StudentResponse.model_validate(student)

        except StudentServiceError as e:
            last_error = e
            # Only retry on duplicate ID errors when auto-generating
            if auto_generate_id and e.code == "duplicate_student_id":
                # Wait a tiny bit to reduce collision chance on retry
                import asyncio
                await asyncio.sleep(0.01 * (attempt + 1))
                continue
            # For other errors or manual IDs, don't retry
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)

    # All retries exhausted
    raise HTTPException(
        status_code=status.HTTP_400_BAD_REQUEST,
        detail=last_error.message if last_error else "Failed to create student after multiple attempts"
    )


@router.get(
    "/generate-id",
    response_model=dict,
    summary="Generate student ID",
    dependencies=[Depends(require_permissions("students.create"))],
)
async def generate_student_id(
    tenant: RequestTenant,
    db: DatabaseSession,
    school_id: Optional[UUID] = Query(default=None, description="School ID to get prefix from"),
) -> dict:
    """Generate a unique student ID for the tenant using school's configured prefix."""
    service = StudentService(db)

    # Get the school's student_id_prefix
    prefix = "STU"  # Default fallback

    if school_id:
        # Fetch prefix from specific school
        result = await db.execute(
            select(School.student_id_prefix).where(School.id == school_id)
        )
        school_prefix = result.scalar_one_or_none()
        if school_prefix:
            prefix = school_prefix
    else:
        # Fetch prefix from tenant's first school (single-school tenants)
        result = await db.execute(
            select(School.student_id_prefix).where(School.tenant_id == tenant.tenant_id).limit(1)
        )
        school_prefix = result.scalar_one_or_none()
        if school_prefix:
            prefix = school_prefix

    try:
        student_id = await service.generate_student_id(tenant.tenant_id, prefix)
        return {"student_id": student_id}
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.get(
    "",
    response_model=dict,
    summary="List students",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def list_students(
    tenant: RequestTenant,
    db: DatabaseSession,
    search: Optional[str] = Query(None, description="Search by name or student ID"),
    class_id: Optional[UUID] = Query(None, description="Filter by class"),
    section_id: Optional[UUID] = Query(None, description="Filter by section"),
    school_id: Optional[UUID] = Query(None, description="Filter by school"),
    status: Optional[str] = Query(None, description="Filter by status"),
    gender: Optional[str] = Query(None, description="Filter by gender"),
    is_boarder: Optional[bool] = Query(None, description="Filter by boarder status"),
    page: int = Query(1, ge=1, description="Page number"),
    page_size: int = Query(20, ge=1, le=100, description="Items per page"),
) -> dict:
    """List students with filters and pagination."""
    service = StudentService(db)
    students, total = await service.list_students(
        tenant_id=tenant.tenant_id,
        search=search,
        class_id=class_id,
        section_id=section_id,
        school_id=school_id,
        status=status,
        gender=gender,
        is_boarder=is_boarder,
        page=page,
        page_size=page_size,
    )

    total_pages = (total + page_size - 1) // page_size if total > 0 else 0

    return {
        "items": [
            StudentListResponse(
                id=s.id,
                student_id=s.student_id,
                previous_student_id=s.previous_student_id,
                first_name=s.first_name,
                middle_name=s.middle_name,
                last_name=s.last_name,
                gender=s.gender.value,
                date_of_birth=s.date_of_birth,
                status=s.status.value,
                class_id=s.class_id,
                class_name=s.class_.name if s.class_ else None,
                section_id=s.section_id,
                section_name=s.section.name if s.section else None,
                photo_url=s.photo_url,
            )
            for s in students
        ],
        "total": total,
        "page": page,
        "page_size": page_size,
        "total_pages": total_pages,
        "has_next": page < total_pages,
        "has_previous": page > 1,
    }


@router.get(
    "/stats",
    response_model=StudentStatsResponse,
    summary="Get student statistics",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_student_stats(
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentStatsResponse:
    """Get student statistics for the tenant."""
    service = StudentService(db)
    stats = await service.get_student_stats(tenant.tenant_id)
    return StudentStatsResponse(**stats)


@router.get(
    "/{student_id}",
    response_model=StudentWithGuardiansResponse,
    summary="Get student details",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_student(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
    include_guardians: bool = Query(True, description="Include guardians"),
) -> StudentWithGuardiansResponse:
    """Get student by ID with optional guardians."""
    service = StudentService(db)
    student = await service.get_student(student_id, include_guardians=include_guardians)

    if not student:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Student not found",
        )

    guardians = []
    if include_guardians:
        for sg in student.guardians:
            guardians.append(
                StudentGuardianResponse(
                    id=sg.id,
                    student_id=sg.student_id,
                    guardian_id=sg.guardian_id,
                    relationship=sg.relation_type.value,
                    is_primary=sg.is_primary,
                    is_emergency_contact=sg.is_emergency_contact,
                    can_pickup=sg.can_pickup,
                    guardian=GuardianResponse.model_validate(sg.guardian_rel),
                    created_at=sg.created_at,
                    updated_at=sg.updated_at,
                )
            )

    return StudentWithGuardiansResponse(
        id=student.id,
        student_id=student.student_id,
        first_name=student.first_name,
        middle_name=student.middle_name,
        last_name=student.last_name,
        date_of_birth=student.date_of_birth,
        gender=student.gender.value,
        email=student.email,
        phone=student.phone,
        address=student.address,
        city=student.city,
        region=student.region,
        ghana_card_number=student.ghana_card_number,
        nhis_number=student.nhis_number,
        school_id=student.school_id,
        class_id=student.class_id,
        section_id=student.section_id,
        admission_date=student.admission_date,
        admission_number=student.admission_number,
        status=student.status.value,
        is_boarder=student.is_boarder,
        blood_group=student.blood_group,
        medical_conditions=student.medical_conditions,
        allergies=student.allergies,
        photo_url=student.photo_url,
        notes=student.notes,
        created_at=student.created_at,
        updated_at=student.updated_at,
        guardians=guardians,
        school_name=student.school.name if student.school else None,
        class_name=student.class_.name if student.class_ else None,
        section_name=student.section.name if student.section else None,
    )


@router.put(
    "/{student_id}",
    response_model=StudentResponse,
    summary="Update student",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def update_student(
    student_id: UUID,
    data: StudentUpdate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentResponse:
    """Update a student."""
    service = StudentService(db)
    student = await service.update_student(
        student_id=student_id,
        **data.model_dump(exclude_unset=True),
    )

    if not student:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Student not found",
        )

    return StudentResponse.model_validate(student)


@router.delete(
    "/{student_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete student",
    dependencies=[Depends(require_permissions("students.delete"))],
)
async def delete_student(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> None:
    """Soft delete a student."""
    service = StudentService(db)
    deleted = await service.delete_student(student_id)

    if not deleted:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Student not found",
        )


@router.post(
    "/bulk",
    response_model=StudentBulkResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Bulk create students",
    dependencies=[Depends(require_permissions("students.create"))],
)
async def bulk_create_students(
    data: StudentBulkCreate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentBulkResponse:
    """Bulk create students."""
    service = StudentService(db)
    result = await service.bulk_create_students(
        tenant_id=tenant.tenant_id,
        students_data=[s.model_dump(exclude={"guardians"}) for s in data.students],
    )
    return StudentBulkResponse(**result)


# Allowed MIME types for import files
ALLOWED_IMPORT_TYPES = {
    "text/csv": "csv",
    "application/vnd.ms-excel": "xls",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
}

# Max file size: 5MB
MAX_IMPORT_SIZE = 5 * 1024 * 1024


@router.post(
    "/import",
    response_model=StudentImportResponse,
    summary="Import students from CSV/Excel",
    description="Import students from a CSV or Excel file. Supports preview mode to validate data before importing.",
    dependencies=[Depends(require_permissions("students.create"))],
)
async def import_students(
    tenant: RequestTenant,
    db: DatabaseSession,
    file: UploadFile = File(..., description="CSV or Excel file with student data"),
    preview: bool = Form(default=False, description="If true, only preview without creating"),
    auto_generate_ids: bool = Form(default=True, description="Auto-generate student IDs for missing ones"),
) -> StudentImportResponse:
    """
    Import students from a CSV or Excel file.

    The file should have a header row with column names. Columns are auto-mapped to student fields.

    Supported columns:
    - student_id (or: student_no, id, admission_no)
    - first_name (or: firstname, first, given_name)
    - middle_name (or: middlename, middle)
    - last_name (or: lastname, surname, family_name)
    - date_of_birth (or: dob, birth_date) - formats: YYYY-MM-DD, DD/MM/YYYY, etc.
    - gender (or: sex) - values: M/F, Male/Female, Boy/Girl
    - email
    - phone (or: mobile, telephone)
    - address
    - city
    - region
    - is_boarder (or: boarder) - values: Yes/No, True/False, 1/0

    Returns preview data in preview mode, or import results in import mode.
    """
    # Validate file type
    content_type = file.content_type or ""
    if content_type not in ALLOWED_IMPORT_TYPES:
        # Try to detect from filename
        filename = file.filename or ""
        if filename.lower().endswith(".csv"):
            file_type = "csv"
        elif filename.lower().endswith(".xlsx"):
            file_type = "xlsx"
        elif filename.lower().endswith(".xls"):
            file_type = "xls"
        else:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Invalid file type. Allowed: CSV, XLS, XLSX. Got: {content_type}",
            )
    else:
        file_type = ALLOWED_IMPORT_TYPES[content_type]

    # Read file content
    content = await file.read()

    # Validate file size
    if len(content) > MAX_IMPORT_SIZE:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"File too large. Maximum size is 5MB. Got: {len(content) / 1024 / 1024:.2f}MB",
        )

    # Validate file is not empty
    if len(content) == 0:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="File is empty",
        )

    # Import students
    service = StudentService(db)
    try:
        result = await service.import_students_from_file(
            tenant_id=tenant.tenant_id,
            file_content=content,
            file_type=file_type,
            preview_only=preview,
            auto_generate_ids=auto_generate_ids,
        )
        return StudentImportResponse(**result)
    except StudentServiceError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=e.message,
        )


@router.get(
    "/import/template",
    summary="Download import template",
    description="Get a CSV template for student import.",
)
async def get_import_template() -> dict:
    """
    Return the CSV template headers for student import.

    Use this to create a properly formatted import file.

    Note: The system always auto-generates a unique student ID (e.g., STU-2026-001).
    Use the previous_student_id column to preserve IDs from previous/external systems.
    """
    return {
        "headers": [
            "previous_student_id",
            "first_name",
            "middle_name",
            "last_name",
            "date_of_birth",
            "gender",
            "email",
            "phone",
            "address",
            "city",
            "region",
            "is_boarder",
        ],
        "example_row": {
            "previous_student_id": "OLD-SYS-001",
            "first_name": "Kofi",
            "middle_name": "Mensah",
            "last_name": "Asante",
            "date_of_birth": "2010-05-15",
            "gender": "male",
            "email": "kofi.asante@example.com",
            "phone": "+233244123456",
            "address": "123 Independence Ave",
            "city": "Accra",
            "region": "Greater Accra",
            "is_boarder": "no",
        },
        "notes": [
            "previous_student_id: Optional - ID from previous/external system for reference",
            "student_id: Auto-generated by system (e.g., STU-2026-001) - not in template",
            "date_of_birth: Supports formats like YYYY-MM-DD, DD/MM/YYYY",
            "gender: Accepts M/F, Male/Female, Boy/Girl",
            "is_boarder: Accepts Yes/No, True/False, 1/0",
        ],
    }


# =========================
# Guardian Endpoints
# =========================


@router.post(
    "/{student_id}/guardians",
    response_model=StudentGuardianResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Add guardian to student",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def add_guardian_to_student(
    student_id: UUID,
    data: StudentGuardianWithNewGuardian,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentGuardianResponse:
    """Create a new guardian and link to student."""
    service = StudentService(db)
    try:
        # First create the guardian
        guardian = await service.create_guardian(
            tenant_id=tenant.tenant_id,
            **data.guardian.model_dump(),
        )

        # Then link to student
        link = await service.link_guardian_to_student(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            guardian_id=guardian.id,
            relationship=data.relationship,
            is_primary=data.is_primary,
            is_emergency_contact=data.is_emergency_contact,
            can_pickup=data.can_pickup,
        )

        return StudentGuardianResponse(
            id=link.id,
            student_id=link.student_id,
            guardian_id=link.guardian_id,
            relationship=link.relation_type.value,
            is_primary=link.is_primary,
            is_emergency_contact=link.is_emergency_contact,
            can_pickup=link.can_pickup,
            guardian=GuardianResponse.model_validate(guardian),
            created_at=link.created_at,
            updated_at=link.updated_at,
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.post(
    "/{student_id}/guardians/link",
    response_model=StudentGuardianResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Link existing guardian to student",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def link_existing_guardian(
    student_id: UUID,
    data: StudentGuardianCreate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentGuardianResponse:
    """Link an existing guardian to a student."""
    service = StudentService(db)
    try:
        link = await service.link_guardian_to_student(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            guardian_id=data.guardian_id,
            relationship=data.relationship,
            is_primary=data.is_primary,
            is_emergency_contact=data.is_emergency_contact,
            can_pickup=data.can_pickup,
        )

        guardian = await service.get_guardian(data.guardian_id)

        return StudentGuardianResponse(
            id=link.id,
            student_id=link.student_id,
            guardian_id=link.guardian_id,
            relationship=link.relation_type.value,
            is_primary=link.is_primary,
            is_emergency_contact=link.is_emergency_contact,
            can_pickup=link.can_pickup,
            guardian=GuardianResponse.model_validate(guardian),
            created_at=link.created_at,
            updated_at=link.updated_at,
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.get(
    "/{student_id}/guardians",
    response_model=list[StudentGuardianResponse],
    summary="Get student's guardians",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_student_guardians(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> list[StudentGuardianResponse]:
    """Get all guardians linked to a student."""
    service = StudentService(db)
    links = await service.get_student_guardians(tenant.tenant_id, student_id)

    return [
        StudentGuardianResponse(
            id=link.id,
            student_id=link.student_id,
            guardian_id=link.guardian_id,
            relationship=link.relation_type.value,
            is_primary=link.is_primary,
            is_emergency_contact=link.is_emergency_contact,
            can_pickup=link.can_pickup,
            guardian=GuardianResponse.model_validate(link.guardian_rel),
            created_at=link.created_at,
            updated_at=link.updated_at,
        )
        for link in links
    ]


@router.put(
    "/{student_id}/guardians/{guardian_id}",
    response_model=StudentGuardianResponse,
    summary="Update guardian link",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def update_guardian_link(
    student_id: UUID,
    guardian_id: UUID,
    data: StudentGuardianUpdate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentGuardianResponse:
    """Update a student-guardian link."""
    service = StudentService(db)

    # Find the link first
    links = await service.get_student_guardians(tenant.tenant_id, student_id)
    link = next((l for l in links if l.guardian_id == guardian_id), None)

    if not link:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Guardian link not found",
        )

    updated_link = await service.update_student_guardian_link(
        link_id=link.id,
        tenant_id=tenant.tenant_id,
        student_id=student_id,
        **data.model_dump(exclude_unset=True),
    )

    guardian = await service.get_guardian(guardian_id)

    return StudentGuardianResponse(
        id=updated_link.id,
        student_id=updated_link.student_id,
        guardian_id=updated_link.guardian_id,
        relationship=updated_link.relation_type.value,
        is_primary=updated_link.is_primary,
        is_emergency_contact=updated_link.is_emergency_contact,
        can_pickup=updated_link.can_pickup,
        guardian=GuardianResponse.model_validate(guardian),
        created_at=updated_link.created_at,
        updated_at=updated_link.updated_at,
    )


@router.delete(
    "/{student_id}/guardians/{guardian_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Unlink guardian from student",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def unlink_guardian(
    student_id: UUID,
    guardian_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> None:
    """Remove a guardian link from a student."""
    service = StudentService(db)
    unlinked = await service.unlink_guardian_from_student(student_id, guardian_id)

    if not unlinked:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Guardian link not found",
        )


# =========================
# Standalone Guardian Endpoints
# =========================


guardians_router = APIRouter()


@guardians_router.post(
    "",
    response_model=GuardianResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create guardian",
    dependencies=[Depends(require_permissions("students.create"))],
)
async def create_guardian(
    data: GuardianCreate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> GuardianResponse:
    """Create a new guardian (without linking to a student)."""
    service = StudentService(db)
    try:
        guardian = await service.create_guardian(
            tenant_id=tenant.tenant_id,
            **data.model_dump(),
        )
        return GuardianResponse.model_validate(guardian)
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@guardians_router.get(
    "",
    response_model=dict,
    summary="List guardians",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def list_guardians(
    tenant: RequestTenant,
    db: DatabaseSession,
    search: Optional[str] = Query(None, description="Search by name, phone, or email"),
    page: int = Query(1, ge=1, description="Page number"),
    page_size: int = Query(20, ge=1, le=100, description="Items per page"),
) -> dict:
    """List guardians with pagination and student counts."""
    service = StudentService(db)
    guardians, total = await service.list_guardians(
        tenant_id=tenant.tenant_id,
        search=search,
        page=page,
        page_size=page_size,
    )

    total_pages = (total + page_size - 1) // page_size if total > 0 else 0

    return {
        "items": guardians,  # Already contains student_count
        "total": total,
        "page": page,
        "page_size": page_size,
        "total_pages": total_pages,
        "has_next": page < total_pages,
        "has_previous": page > 1,
    }


@guardians_router.get(
    "/{guardian_id}",
    response_model=GuardianResponse,
    summary="Get guardian details",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_guardian(
    guardian_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> GuardianResponse:
    """Get guardian by ID."""
    service = StudentService(db)
    guardian = await service.get_guardian(guardian_id)

    if not guardian:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Guardian not found",
        )

    return GuardianResponse.model_validate(guardian)


@guardians_router.put(
    "/{guardian_id}",
    response_model=GuardianResponse,
    summary="Update guardian",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def update_guardian(
    guardian_id: UUID,
    data: GuardianUpdate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> GuardianResponse:
    """Update a guardian."""
    service = StudentService(db)
    guardian = await service.update_guardian(
        guardian_id=guardian_id,
        **data.model_dump(exclude_unset=True),
    )

    if not guardian:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Guardian not found",
        )

    return GuardianResponse.model_validate(guardian)


@guardians_router.delete(
    "/{guardian_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete guardian",
    dependencies=[Depends(require_permissions("students.delete"))],
)
async def delete_guardian(
    guardian_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> None:
    """Soft delete a guardian."""
    service = StudentService(db)
    try:
        deleted = await service.delete_guardian(guardian_id)

        if not deleted:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Guardian not found",
            )
    except StudentServiceError as e:
        if e.code == "guardian_has_linked_students":
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=str(e),
            )
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )


@guardians_router.get(
    "/{guardian_id}/students",
    response_model=list[StudentListResponse],
    summary="Get guardian's students",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_guardian_students(
    guardian_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> list[StudentListResponse]:
    """Get all students linked to a guardian."""
    service = StudentService(db)
    links = await service.get_guardian_students(tenant.tenant_id, guardian_id)

    return [
        StudentListResponse(
            id=link.student_rel.id,
            student_id=link.student_rel.student_id,
            previous_student_id=link.student_rel.previous_student_id,
            first_name=link.student_rel.first_name,
            middle_name=link.student_rel.middle_name,
            last_name=link.student_rel.last_name,
            gender=link.student_rel.gender.value,
            date_of_birth=link.student_rel.date_of_birth,
            status=link.student_rel.status.value,
            class_id=link.student_rel.class_id,
            class_name=None,  # Would need to load class relationship
            section_id=link.student_rel.section_id,
            section_name=None,  # Would need to load section relationship
            photo_url=link.student_rel.photo_url,
        )
        for link in links
    ]
