"""
SIMS Plus - Students Endpoints

API endpoints for student management.
"""

from typing import Optional
from uuid import UUID

import csv
import io

from fastapi import APIRouter, Depends, File, Form, HTTPException, Query, UploadFile, status
from fastapi.responses import Response, StreamingResponse

from sqlalchemy import select

from app.api.deps import (
    DatabaseSession,
    RequestTenant,
    ValidatedUser,
    require_permissions,
)
from app.models.school import School
from app.schemas.student import (
    # Guardian
    GuardianCreate,
    GuardianUpdate,
    GuardianResponse,
    GuardianListResponse,
    # Student-Guardian
    StudentGuardianCreate,
    StudentGuardianWithNewGuardian,
    StudentGuardianUpdate,
    StudentGuardianResponse,
    # Student
    StudentCreate,
    StudentUpdate,
    StudentResponse,
    StudentWithGuardiansResponse,
    StudentListResponse,
    StudentBulkCreate,
    StudentBulkResponse,
    StudentStatsResponse,
    StudentImportResponse,
    # Promotion
    StudentPromotionRequest,
    StudentPromotionResponse,
    # History & Analytics
    StudentClassHistoryListResponse,
    StudentClassHistoryResponse,
    StudentStatusChangeListResponse,
    StudentStatusChangeResponse,
    EnrollmentAnalyticsResponse,
    # Lifecycle (Withdrawal / Transfer)
    OutstandingFeeCheckResponse,
    WithdrawalInitiateRequest,
    WithdrawalClearanceResponse,
    WithdrawalClearanceUpdateRequest,
    WithdrawalCompleteResponse,
    TransferInitiateRequest,
    ChainTransferRequest,
    ChainTransferResponse,
    # Documents & Previous Schools
    StudentDocumentUploadResponse,
    StudentDocumentListResponse,
    StudentDocumentDownloadResponse,
    PreviousSchoolCreate,
    PreviousSchoolUpdate,
    PreviousSchoolResponse,
    StructuredMedical,
)
from app.models.student import StudentDocumentType
from app.services.student import StudentService, StudentServiceError

router = APIRouter()


# =========================
# Student Endpoints
# =========================


@router.post(
    "",
    response_model=StudentResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create student",
    dependencies=[Depends(require_permissions("students.create"))],
)
async def create_student(
    data: StudentCreate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentResponse:
    """Create a new student.

    Note: student_id is always auto-generated by the system.
    Use previous_student_id to store IDs from external/previous systems.
    """
    service = StudentService(db)

    max_retries = 5

    # Get school's student_id_prefix for auto-generation
    prefix = "STU"  # Default
    if data.school_id:
        # Defense-in-depth: scope school lookup to tenant
        school_result = await db.execute(
            select(School.student_id_prefix).where(
                School.id == data.school_id,
                School.tenant_id == tenant.tenant_id,
            )
        )
        school_prefix = school_result.scalar_one_or_none()
        if school_prefix:
            prefix = school_prefix
    else:
        # Get first school for tenant
        school_result = await db.execute(
            select(School.student_id_prefix).where(School.tenant_id == tenant.tenant_id).limit(1)
        )
        school_prefix = school_result.scalar_one_or_none()
        if school_prefix:
            prefix = school_prefix

    # Convert guardians to dict format if provided
    guardians_data = None
    if data.guardians:
        guardians_data = [
            {
                "guardian": g.guardian.model_dump(),
                "relationship": g.relationship,
                "is_primary": g.is_primary,
                "is_emergency_contact": g.is_emergency_contact,
                "can_pickup": g.can_pickup,
            }
            for g in data.guardians
        ]

    # Retry loop for handling concurrent ID generation conflicts
    last_error = None
    for attempt in range(max_retries):
        try:
            # Always auto-generate student ID
            student_id = await service.generate_student_id(tenant.tenant_id, prefix)

            student = await service.create_student(
                tenant_id=tenant.tenant_id,
                student_id=student_id,
                previous_student_id=data.previous_student_id,
                first_name=data.first_name,
                middle_name=data.middle_name,
                last_name=data.last_name,
                date_of_birth=data.date_of_birth,
                gender=data.gender,
                email=data.email,
                phone=data.phone,
                address=data.address,
                city=data.city,
                region=data.region,
                ghana_card_number=data.ghana_card_number,
                nhis_number=data.nhis_number,
                school_id=data.school_id,
                class_id=data.class_id,
                section_id=data.section_id,
                admission_date=data.admission_date,
                admission_number=data.admission_number,
                status=data.status,
                is_boarder=data.is_boarder,
                blood_group=data.blood_group,
                medical_conditions=data.medical_conditions,
                allergies=data.allergies,
                photo_url=data.photo_url,
                notes=data.notes,
                guardians=guardians_data,
            )
            return StudentResponse.model_validate(student)

        except StudentServiceError as e:
            last_error = e
            # Retry on duplicate ID errors (student IDs are always auto-generated)
            if e.code == "duplicate_student_id":
                # Wait a tiny bit to reduce collision chance on retry
                import asyncio
                await asyncio.sleep(0.01 * (attempt + 1))
                continue
            # For other errors, don't retry
            raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)

    # All retries exhausted
    raise HTTPException(
        status_code=status.HTTP_400_BAD_REQUEST,
        detail=last_error.message if last_error else "Failed to create student after multiple attempts"
    )


@router.get(
    "/generate-id",
    response_model=dict,
    summary="Generate student ID",
    dependencies=[Depends(require_permissions("students.create"))],
)
async def generate_student_id(
    tenant: RequestTenant,
    db: DatabaseSession,
    school_id: Optional[UUID] = Query(default=None, description="School ID to get prefix from"),
) -> dict:
    """Generate a unique student ID for the tenant using school's configured prefix."""
    service = StudentService(db)

    # Get the school's student_id_prefix
    prefix = "STU"  # Default fallback

    if school_id:
        # Defense-in-depth: scope school lookup to tenant
        result = await db.execute(
            select(School.student_id_prefix).where(
                School.id == school_id,
                School.tenant_id == tenant.tenant_id,
            )
        )
        school_prefix = result.scalar_one_or_none()
        if school_prefix:
            prefix = school_prefix
    else:
        # Fetch prefix from tenant's first school (single-school tenants)
        result = await db.execute(
            select(School.student_id_prefix).where(School.tenant_id == tenant.tenant_id).limit(1)
        )
        school_prefix = result.scalar_one_or_none()
        if school_prefix:
            prefix = school_prefix

    try:
        student_id = await service.generate_student_id(tenant.tenant_id, prefix)
        return {"student_id": student_id}
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.get(
    "",
    response_model=dict,
    summary="List students",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def list_students(
    tenant: RequestTenant,
    db: DatabaseSession,
    search: Optional[str] = Query(None, description="Search by name or student ID"),
    class_id: Optional[UUID] = Query(None, description="Filter by class"),
    section_id: Optional[UUID] = Query(None, description="Filter by section"),
    school_id: Optional[UUID] = Query(None, description="Filter by school"),
    status: Optional[str] = Query(None, description="Filter by status"),
    gender: Optional[str] = Query(None, description="Filter by gender"),
    is_boarder: Optional[bool] = Query(None, description="Filter by boarder status"),
    page: int = Query(1, ge=1, description="Page number"),
    page_size: int = Query(20, ge=1, le=100, description="Items per page"),
) -> dict:
    """List students with filters and pagination."""
    service = StudentService(db)
    students, total = await service.list_students(
        tenant_id=tenant.tenant_id,
        search=search,
        class_id=class_id,
        section_id=section_id,
        school_id=school_id,
        status=status,
        gender=gender,
        is_boarder=is_boarder,
        page=page,
        page_size=page_size,
    )

    total_pages = (total + page_size - 1) // page_size if total > 0 else 0

    return {
        "items": [
            StudentListResponse(
                id=s.id,
                student_id=s.student_id,
                previous_student_id=s.previous_student_id,
                first_name=s.first_name,
                middle_name=s.middle_name,
                last_name=s.last_name,
                gender=s.gender.value,
                date_of_birth=s.date_of_birth,
                status=s.status.value,
                class_id=s.class_id,
                class_name=s.class_.name if s.class_ else None,
                section_id=s.section_id,
                section_name=s.section.name if s.section else None,
                photo_url=s.photo_url,
            )
            for s in students
        ],
        "total": total,
        "page": page,
        "page_size": page_size,
        "total_pages": total_pages,
        "has_next": page < total_pages,
        "has_previous": page > 1,
    }


@router.get(
    "/stats",
    response_model=StudentStatsResponse,
    summary="Get student statistics",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_student_stats(
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentStatsResponse:
    """Get student statistics for the tenant."""
    service = StudentService(db)
    stats = await service.get_student_stats(tenant.tenant_id)
    return StudentStatsResponse(**stats)


@router.get(
    "/enrollment-analytics",
    response_model=EnrollmentAnalyticsResponse,
    summary="Get enrollment analytics",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_enrollment_analytics(
    tenant: RequestTenant,
    db: DatabaseSession,
    school_id: Optional[UUID] = Query(None, description="School ID (required for chain tenants)"),
) -> EnrollmentAnalyticsResponse:
    """Get enhanced enrollment analytics with status counts, class breakdown, and trends.

    For single-school tenants, school_id is resolved automatically.
    For chain tenants, school_id must be provided.
    """
    service = StudentService(db)

    # Resolve school_id: use provided value, or look up first school for tenant
    resolved_school_id = school_id
    if not resolved_school_id:
        school_result = await db.execute(
            select(School.id).where(School.tenant_id == tenant.tenant_id).limit(1)
        )
        resolved_school_id = school_result.scalar_one_or_none()
        if not resolved_school_id:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="No school found for this tenant. Provide school_id.",
            )

    try:
        analytics = await service.get_enrollment_analytics(
            tenant_id=tenant.tenant_id,
            school_id=resolved_school_id,
        )
        return EnrollmentAnalyticsResponse(**analytics)
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.get(
    "/export",
    summary="Export students as CSV",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def export_students_csv(
    tenant: RequestTenant,
    db: DatabaseSession,
    class_id: Optional[UUID] = Query(None),
    section_id: Optional[UUID] = Query(None),
) -> StreamingResponse:
    """Export students as CSV file."""
    service = StudentService(db)
    rows = await service.export_students_csv(
        tenant_id=tenant.tenant_id,
        class_id=class_id,
        section_id=section_id,
    )

    output = io.StringIO()
    if rows:
        writer = csv.DictWriter(output, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)
    else:
        # Write just headers for empty export
        writer = csv.DictWriter(
            output,
            fieldnames=["student_id", "first_name", "middle_name", "last_name",
                        "date_of_birth", "gender", "email", "phone", "address",
                        "city", "region", "class_name", "section_name", "status"],
        )
        writer.writeheader()

    output.seek(0)
    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="students_export.csv"'},
    )


@router.post(
    "/bulk/promote",
    response_model=StudentPromotionResponse,
    summary="Promote students between classes",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def promote_students(
    data: StudentPromotionRequest,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentPromotionResponse:
    """Bulk promote students from one class to another."""
    service = StudentService(db)
    try:
        result = await service.promote_students(
            tenant_id=tenant.tenant_id,
            from_class_id=data.from_class_id,
            to_class_id=data.to_class_id,
            student_ids=data.student_ids,
        )
        return StudentPromotionResponse(**result)
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.get(
    "/{student_id}",
    response_model=StudentWithGuardiansResponse,
    summary="Get student details",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_student(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
    include_guardians: bool = Query(True, description="Include guardians"),
) -> StudentWithGuardiansResponse:
    """Get student by ID with optional guardians."""
    service = StudentService(db)
    student = await service.get_student(tenant.tenant_id, student_id, include_guardians=include_guardians)

    if not student:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Student not found",
        )

    guardians = []
    if include_guardians:
        for sg in student.guardians:
            guardians.append(
                StudentGuardianResponse(
                    id=sg.id,
                    student_id=sg.student_id,
                    guardian_id=sg.guardian_id,
                    relationship=sg.relation_type.value,
                    is_primary=sg.is_primary,
                    is_emergency_contact=sg.is_emergency_contact,
                    can_pickup=sg.can_pickup,
                    guardian=GuardianResponse.model_validate(sg.guardian_rel),
                    created_at=sg.created_at,
                    updated_at=sg.updated_at,
                )
            )

    return StudentWithGuardiansResponse(
        id=student.id,
        student_id=student.student_id,
        first_name=student.first_name,
        middle_name=student.middle_name,
        last_name=student.last_name,
        date_of_birth=student.date_of_birth,
        gender=student.gender.value,
        email=student.email,
        phone=student.phone,
        address=student.address,
        city=student.city,
        region=student.region,
        ghana_card_number=student.ghana_card_number,
        nhis_number=student.nhis_number,
        school_id=student.school_id,
        class_id=student.class_id,
        section_id=student.section_id,
        admission_date=student.admission_date,
        admission_number=student.admission_number,
        status=student.status.value,
        is_boarder=student.is_boarder,
        blood_group=student.blood_group,
        medical_conditions=student.medical_conditions,
        allergies=student.allergies,
        photo_url=student.photo_url,
        notes=student.notes,
        created_at=student.created_at,
        updated_at=student.updated_at,
        guardians=guardians,
        school_name=student.school.name if student.school else None,
        class_name=student.class_.name if student.class_ else None,
        section_name=student.section.name if student.section else None,
    )


@router.put(
    "/{student_id}",
    response_model=StudentResponse,
    summary="Update student",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def update_student(
    student_id: UUID,
    data: StudentUpdate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentResponse:
    """Update a student."""
    service = StudentService(db)
    student = await service.update_student(
        tenant_id=tenant.tenant_id,
        student_id=student_id,
        **data.model_dump(exclude_unset=True),
    )

    if not student:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Student not found",
        )

    return StudentResponse.model_validate(student)


@router.delete(
    "/{student_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete student",
    dependencies=[Depends(require_permissions("students.delete"))],
)
async def delete_student(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> None:
    """Soft delete a student."""
    service = StudentService(db)
    deleted = await service.delete_student(tenant.tenant_id, student_id)

    if not deleted:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Student not found",
        )


@router.get(
    "/{student_id}/class-history",
    response_model=StudentClassHistoryListResponse,
    summary="Get student class assignment history",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_student_class_history(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentClassHistoryListResponse:
    """Get the full class assignment history for a student.

    Returns every class/section a student has been enrolled in, ordered
    by enrolled_date descending (most recent first).
    """
    service = StudentService(db)

    # Verify student exists and belongs to tenant
    student = await service.get_student(tenant.tenant_id, student_id)
    if not student:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Student not found",
        )

    records = await service.get_class_history(
        tenant_id=tenant.tenant_id,
        student_id=student_id,
    )
    return StudentClassHistoryListResponse(
        records=[StudentClassHistoryResponse(**r) for r in records],
        total=len(records),
    )


@router.get(
    "/{student_id}/status-history",
    response_model=StudentStatusChangeListResponse,
    summary="Get student status change history",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_student_status_history(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentStatusChangeListResponse:
    """Get the full status change timeline for a student.

    Returns every enrollment status transition (e.g., active -> suspended),
    ordered by created_at descending (most recent first).
    """
    service = StudentService(db)

    # Verify student exists and belongs to tenant
    student = await service.get_student(tenant.tenant_id, student_id)
    if not student:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Student not found",
        )

    records = await service.get_status_history(
        tenant_id=tenant.tenant_id,
        student_id=student_id,
    )
    return StudentStatusChangeListResponse(
        records=[StudentStatusChangeResponse(**r) for r in records],
        total=len(records),
    )


# =========================
# Lifecycle Endpoints (Withdrawal / Transfer)
# =========================


@router.get(
    "/{student_id}/outstanding-fees",
    response_model=OutstandingFeeCheckResponse,
    summary="Check outstanding fees",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def check_outstanding_fees(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> OutstandingFeeCheckResponse:
    """Check outstanding invoices for a student.

    Returns advisory fee information -- does not block any action.
    """
    service = StudentService(db)
    try:
        result = await service.check_outstanding_fees(tenant.tenant_id, student_id)
        return OutstandingFeeCheckResponse(**result)
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.post(
    "/{student_id}/withdraw",
    response_model=dict,
    summary="Initiate student withdrawal",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def initiate_withdrawal(
    student_id: UUID,
    data: WithdrawalInitiateRequest,
    tenant: RequestTenant,
    db: DatabaseSession,
    current_user: ValidatedUser,
) -> dict:
    """Start the withdrawal process by creating a clearance checklist.

    The student status is NOT changed until complete_withdrawal is called.
    """
    service = StudentService(db)

    # Resolve school_id for the student
    school_id = await _resolve_school_id(db, tenant.tenant_id)

    try:
        result = await service.initiate_withdrawal(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            school_id=school_id,
            reason=data.reason,
            effective_date=data.effective_date,
            performed_by=current_user["user_id"],
            fee_override=data.fee_override,
        )
        return result
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.get(
    "/{student_id}/withdrawal-clearance",
    response_model=WithdrawalClearanceResponse,
    summary="Get withdrawal clearance",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_withdrawal_clearance(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> WithdrawalClearanceResponse:
    """Get the pending withdrawal/transfer clearance for a student."""
    service = StudentService(db)
    clearance = await service.get_withdrawal_clearance(tenant.tenant_id, student_id)
    if not clearance:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No pending clearance found for this student",
        )
    return WithdrawalClearanceResponse(
        id=clearance.id,
        student_id=clearance.student_id,
        status_change_id=clearance.status_change_id,
        type=clearance.type,
        library_cleared=clearance.library_cleared,
        finance_cleared=clearance.finance_cleared,
        property_cleared=clearance.property_cleared,
        boarding_cleared=clearance.boarding_cleared,
        outstanding_fees=float(clearance.outstanding_fees) if clearance.outstanding_fees else None,
        fee_override=clearance.fee_override,
        notes=clearance.notes,
        is_complete=clearance.is_complete,
        cleared_by=clearance.cleared_by,
        cleared_at=clearance.cleared_at.isoformat() if clearance.cleared_at else None,
        created_at=clearance.created_at.isoformat() if clearance.created_at else "",
    )


@router.patch(
    "/{student_id}/withdrawal-clearance/{clearance_id}",
    response_model=WithdrawalClearanceResponse,
    summary="Update clearance items",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def update_clearance(
    student_id: UUID,
    clearance_id: UUID,
    data: WithdrawalClearanceUpdateRequest,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> WithdrawalClearanceResponse:
    """Update withdrawal/transfer clearance checklist items.

    Auto-completes the clearance when all required items are cleared.
    """
    service = StudentService(db)
    try:
        clearance = await service.update_clearance(
            tenant_id=tenant.tenant_id,
            clearance_id=clearance_id,
            student_id=student_id,
            **data.model_dump(exclude_unset=True),
        )
        return WithdrawalClearanceResponse(
            id=clearance.id,
            student_id=clearance.student_id,
            status_change_id=clearance.status_change_id,
            type=clearance.type,
            library_cleared=clearance.library_cleared,
            finance_cleared=clearance.finance_cleared,
            property_cleared=clearance.property_cleared,
            boarding_cleared=clearance.boarding_cleared,
            outstanding_fees=float(clearance.outstanding_fees) if clearance.outstanding_fees else None,
            fee_override=clearance.fee_override,
            notes=clearance.notes,
            is_complete=clearance.is_complete,
            cleared_by=clearance.cleared_by,
            cleared_at=clearance.cleared_at.isoformat() if clearance.cleared_at else None,
            created_at=clearance.created_at.isoformat() if clearance.created_at else "",
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.post(
    "/{student_id}/complete-withdrawal",
    response_model=WithdrawalCompleteResponse,
    summary="Complete student withdrawal",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def complete_withdrawal(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
    current_user: ValidatedUser,
) -> WithdrawalCompleteResponse:
    """Finalize the withdrawal after clearance is complete.

    Changes student status to 'withdrawn' and records the status change.
    """
    service = StudentService(db)
    try:
        student = await service.complete_withdrawal(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            performed_by=current_user["user_id"],
        )
        return WithdrawalCompleteResponse(
            student_id=student.id,
            status=student.status.value,
            clearance_completed=True,
            withdrawal_letter_available=True,
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.post(
    "/{student_id}/transfer",
    response_model=dict,
    summary="Initiate external transfer",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def initiate_transfer(
    student_id: UUID,
    data: TransferInitiateRequest,
    tenant: RequestTenant,
    db: DatabaseSession,
    current_user: ValidatedUser,
) -> dict:
    """Start an external transfer process with clearance checklist.

    The student status is NOT changed until complete_transfer is called.
    """
    service = StudentService(db)

    school_id = await _resolve_school_id(db, tenant.tenant_id)

    try:
        result = await service.initiate_transfer(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            school_id=school_id,
            destination_school=data.destination_school,
            reason=data.reason,
            effective_date=data.effective_date,
            performed_by=current_user["user_id"],
            fee_override=data.fee_override,
        )
        return result
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.post(
    "/{student_id}/complete-transfer",
    response_model=StudentResponse,
    summary="Complete external transfer",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def complete_transfer(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
    current_user: ValidatedUser,
) -> StudentResponse:
    """Finalize an external transfer.

    Changes student status to 'transferred' and records the status change.
    """
    service = StudentService(db)
    try:
        student = await service.complete_transfer(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            performed_by=current_user["user_id"],
        )
        return StudentResponse.model_validate(student)
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.post(
    "/{student_id}/chain-transfer",
    response_model=ChainTransferResponse,
    summary="Transfer student within school chain",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def chain_transfer(
    student_id: UUID,
    data: ChainTransferRequest,
    tenant: RequestTenant,
    db: DatabaseSession,
    current_user: ValidatedUser,
) -> ChainTransferResponse:
    """Transfer a student between schools in the same chain.

    Student remains ACTIVE with updated school/class/section.
    """
    service = StudentService(db)

    # Resolve the student's current school as the from_school
    student = await service.get_student(tenant.tenant_id, student_id)
    if not student:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail="Student not found"
        )
    if not student.school_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Student does not have a current school assignment",
        )

    try:
        updated = await service.transfer_within_chain(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            from_school_id=student.school_id,
            to_school_id=data.to_school_id,
            to_class_id=data.to_class_id,
            to_section_id=data.to_section_id,
            reason=data.reason,
            effective_date=data.effective_date,
            performed_by=current_user["user_id"],
            fee_override=data.fee_override,
        )
        return ChainTransferResponse(
            student_id=updated.id,
            from_school_id=student.school_id,
            to_school_id=data.to_school_id,
            to_class_id=data.to_class_id,
            status=updated.status.value,
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.get(
    "/{student_id}/transfer-certificate",
    summary="Generate transfer certificate PDF",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_transfer_certificate(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> Response:
    """Generate and download a transfer certificate as PDF."""
    service = StudentService(db)
    try:
        pdf_bytes = await service.generate_transfer_certificate(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
        )
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={
                "Content-Disposition": f'attachment; filename="transfer_certificate_{student_id}.pdf"'
            },
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.get(
    "/{student_id}/export-record",
    summary="Export student record",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def export_student_record(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
    format: str = Query("json", pattern="^(json|pdf)$", description="Export format: json or pdf"),
) -> Response:
    """Export a comprehensive student record as JSON or PDF.

    Includes personal info, class history, status history, academic summary, and finance summary.
    """
    service = StudentService(db)
    try:
        data = await service.export_student_record(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            format=format,
        )
        if format == "pdf":
            return Response(
                content=data,
                media_type="application/pdf",
                headers={
                    "Content-Disposition": f'attachment; filename="student_record_{student_id}.pdf"'
                },
            )
        return Response(
            content=data,
            media_type="application/json",
            headers={
                "Content-Disposition": f'attachment; filename="student_record_{student_id}.json"'
            },
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


# =========================
# Document Endpoints
# =========================


# Map service error codes to HTTP status codes for document/previous school operations
_ERROR_CODE_STATUS_MAP = {
    "student_not_found": status.HTTP_404_NOT_FOUND,
    "document_not_found": status.HTTP_404_NOT_FOUND,
    "previous_school_not_found": status.HTTP_404_NOT_FOUND,
}


def _error_status(e: StudentServiceError) -> int:
    """Resolve HTTP status code from a StudentServiceError code."""
    return _ERROR_CODE_STATUS_MAP.get(e.code, status.HTTP_400_BAD_REQUEST)


@router.post(
    "/{student_id}/documents",
    response_model=StudentDocumentUploadResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Upload student document",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def upload_student_document(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
    current_user: ValidatedUser,
    file: UploadFile = File(..., description="Document file (PDF, JPEG, PNG, DOC, DOCX)"),
    document_type: str = Form(..., description="Document type"),
    title: str = Form(..., description="Document title"),
    notes: str = Form(default="", description="Optional notes"),
) -> StudentDocumentUploadResponse:
    """Upload a document for a student.

    Validates MIME type (PDF, JPEG, PNG, DOC, DOCX) and file size (max 10MB).
    Verifies magic bytes to prevent Content-Type spoofing.
    """
    # Validate document_type enum value
    try:
        doc_type_enum = StudentDocumentType(document_type)
    except ValueError:
        valid_types = [t.value for t in StudentDocumentType]
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid document_type. Must be one of: {', '.join(valid_types)}",
        )

    # Read file content
    content = await file.read()
    file_size = len(content)
    mime_type = file.content_type or "application/octet-stream"
    filename = file.filename or "document"

    # Resolve school_id for the student
    school_id = await _resolve_school_id(db, tenant.tenant_id)

    service = StudentService(db)
    try:
        document = await service.upload_document(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            school_id=school_id,
            document_type=doc_type_enum,
            title=title.strip(),
            file_content=content,
            filename=filename,
            mime_type=mime_type,
            file_size=file_size,
            uploaded_by=current_user["user_id"],
            notes=notes.strip() if notes.strip() else None,
        )
        return StudentDocumentUploadResponse(
            id=document.id,
            student_id=document.student_id,
            document_type=document.document_type.value,
            title=document.title,
            file_size=document.file_size,
            mime_type=document.mime_type,
            uploaded_by=document.uploaded_by,
            notes=document.notes,
            created_at=document.created_at.isoformat() if document.created_at else "",
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=_error_status(e), detail=e.message)


@router.get(
    "/{student_id}/documents",
    response_model=StudentDocumentListResponse,
    summary="List student documents",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def list_student_documents(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
    document_type: Optional[str] = Query(None, description="Filter by document type"),
) -> StudentDocumentListResponse:
    """List all documents for a student, optionally filtered by type."""
    # Parse optional document_type filter
    doc_type_enum = None
    if document_type:
        try:
            doc_type_enum = StudentDocumentType(document_type)
        except ValueError:
            valid_types = [t.value for t in StudentDocumentType]
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Invalid document_type. Must be one of: {', '.join(valid_types)}",
            )

    service = StudentService(db)
    try:
        result = await service.list_documents(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            document_type=doc_type_enum,
        )
        return StudentDocumentListResponse(
            documents=[
                StudentDocumentUploadResponse(
                    id=doc.id,
                    student_id=doc.student_id,
                    document_type=doc.document_type.value,
                    title=doc.title,
                    file_size=doc.file_size,
                    mime_type=doc.mime_type,
                    uploaded_by=doc.uploaded_by,
                    notes=doc.notes,
                    created_at=doc.created_at.isoformat() if doc.created_at else "",
                )
                for doc in result["documents"]
            ],
            total=result["total"],
            total_size_bytes=result["total_size_bytes"],
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=_error_status(e), detail=e.message)


@router.delete(
    "/{student_id}/documents/{document_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete student document",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def delete_student_document(
    student_id: UUID,
    document_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
    current_user: ValidatedUser,
) -> None:
    """Soft-delete a student document.

    IDOR protection: verifies the document belongs to the specified student.
    """
    service = StudentService(db)
    try:
        await service.delete_document(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            document_id=document_id,
            deleted_by=current_user["user_id"],
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=_error_status(e), detail=e.message)


@router.get(
    "/{student_id}/documents/{document_id}/download",
    response_model=StudentDocumentDownloadResponse,
    summary="Get document download URL",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_document_download_url(
    student_id: UUID,
    document_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentDocumentDownloadResponse:
    """Generate a presigned S3 download URL for a student document.

    URL expires in 15 minutes (900 seconds).
    IDOR protection: verifies the document belongs to the specified student.
    """
    service = StudentService(db)
    try:
        result = await service.get_document_download_url(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            document_id=document_id,
        )
        return StudentDocumentDownloadResponse(**result)
    except StudentServiceError as e:
        raise HTTPException(status_code=_error_status(e), detail=e.message)


# =========================
# Previous School Endpoints
# =========================


@router.post(
    "/{student_id}/previous-schools",
    response_model=PreviousSchoolResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Add previous school record",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def create_previous_school(
    student_id: UUID,
    data: PreviousSchoolCreate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> PreviousSchoolResponse:
    """Create a previous school record for a student."""
    school_id = await _resolve_school_id(db, tenant.tenant_id)

    service = StudentService(db)
    try:
        record = await service.add_previous_school(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            school_id=school_id,
            school_name=data.school_name,
            school_address=data.school_address,
            last_class=data.last_class,
            years_attended=data.years_attended,
            transfer_reason=data.transfer_reason,
            leaving_certificate_ref=data.leaving_certificate_ref,
        )
        return PreviousSchoolResponse(
            id=record.id,
            student_id=record.student_id,
            school_name=record.school_name,
            school_address=record.school_address,
            last_class=record.last_class,
            years_attended=record.years_attended,
            transfer_reason=record.transfer_reason,
            leaving_certificate_ref=record.leaving_certificate_ref,
            created_at=record.created_at.isoformat() if record.created_at else "",
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=_error_status(e), detail=e.message)


@router.get(
    "/{student_id}/previous-schools",
    response_model=list[PreviousSchoolResponse],
    summary="List previous schools",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def list_previous_schools(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> list[PreviousSchoolResponse]:
    """List all previous school records for a student."""
    service = StudentService(db)
    try:
        records = await service.list_previous_schools(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
        )
        return [
            PreviousSchoolResponse(
                id=r.id,
                student_id=r.student_id,
                school_name=r.school_name,
                school_address=r.school_address,
                last_class=r.last_class,
                years_attended=r.years_attended,
                transfer_reason=r.transfer_reason,
                leaving_certificate_ref=r.leaving_certificate_ref,
                created_at=r.created_at.isoformat() if r.created_at else "",
            )
            for r in records
        ]
    except StudentServiceError as e:
        raise HTTPException(status_code=_error_status(e), detail=e.message)


@router.put(
    "/{student_id}/previous-schools/{record_id}",
    response_model=PreviousSchoolResponse,
    summary="Update previous school record",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def update_previous_school(
    student_id: UUID,
    record_id: UUID,
    data: PreviousSchoolUpdate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> PreviousSchoolResponse:
    """Update a previous school record.

    IDOR protection: verifies the record belongs to the specified student.
    """
    service = StudentService(db)
    try:
        record = await service.update_previous_school(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            record_id=record_id,
            **data.model_dump(exclude_unset=True),
        )
        return PreviousSchoolResponse(
            id=record.id,
            student_id=record.student_id,
            school_name=record.school_name,
            school_address=record.school_address,
            last_class=record.last_class,
            years_attended=record.years_attended,
            transfer_reason=record.transfer_reason,
            leaving_certificate_ref=record.leaving_certificate_ref,
            created_at=record.created_at.isoformat() if record.created_at else "",
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=_error_status(e), detail=e.message)


@router.delete(
    "/{student_id}/previous-schools/{record_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete previous school record",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def delete_previous_school(
    student_id: UUID,
    record_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> None:
    """Hard-delete a previous school record.

    IDOR protection: verifies the record belongs to the specified student.
    """
    service = StudentService(db)
    try:
        await service.delete_previous_school(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            record_id=record_id,
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=_error_status(e), detail=e.message)


@router.put(
    "/{student_id}/structured-medical",
    summary="Update structured medical data",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def update_structured_medical(
    student_id: UUID,
    data: StructuredMedical,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentResponse:
    """Update the structured medical JSONB field for a student.

    Syncs data to legacy text fields for backward compatibility.
    F-13: Input is validated and sanitized via StructuredMedical schema.
    """
    service = StudentService(db)
    try:
        student = await service.update_structured_medical(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            medical_data=data.model_dump(),
        )
        return StudentResponse.model_validate(student)
    except StudentServiceError as e:
        raise HTTPException(status_code=_error_status(e), detail=e.message)


async def _resolve_school_id(db, tenant_id: UUID) -> UUID:
    """Resolve the school ID for the tenant (single-school shortcut)."""
    result = await db.execute(
        select(School.id).where(School.tenant_id == tenant_id).limit(1)
    )
    school_id = result.scalar_one_or_none()
    if not school_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No school found for this tenant",
        )
    return school_id


@router.post(
    "/bulk",
    response_model=StudentBulkResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Bulk create students",
    dependencies=[Depends(require_permissions("students.create"))],
)
async def bulk_create_students(
    data: StudentBulkCreate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentBulkResponse:
    """Bulk create students."""
    service = StudentService(db)
    result = await service.bulk_create_students(
        tenant_id=tenant.tenant_id,
        students_data=[s.model_dump(exclude={"guardians"}) for s in data.students],
    )
    return StudentBulkResponse(**result)


# Allowed MIME types for import files
ALLOWED_IMPORT_TYPES = {
    "text/csv": "csv",
    "application/vnd.ms-excel": "xls",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
}

# Max file size: 5MB
MAX_IMPORT_SIZE = 5 * 1024 * 1024


@router.post(
    "/import",
    response_model=StudentImportResponse,
    summary="Import students from CSV/Excel",
    description="Import students from a CSV or Excel file. Supports preview mode to validate data before importing.",
    dependencies=[Depends(require_permissions("students.create"))],
)
async def import_students(
    tenant: RequestTenant,
    db: DatabaseSession,
    file: UploadFile = File(..., description="CSV or Excel file with student data"),
    preview: bool = Form(default=False, description="If true, only preview without creating"),
    auto_generate_ids: bool = Form(default=True, description="Auto-generate student IDs for missing ones"),
) -> StudentImportResponse:
    """
    Import students from a CSV or Excel file.

    The file should have a header row with column names. Columns are auto-mapped to student fields.

    Supported columns:
    - student_id (or: student_no, id, admission_no)
    - first_name (or: firstname, first, given_name)
    - middle_name (or: middlename, middle)
    - last_name (or: lastname, surname, family_name)
    - date_of_birth (or: dob, birth_date) - formats: YYYY-MM-DD, DD/MM/YYYY, etc.
    - gender (or: sex) - values: M/F, Male/Female, Boy/Girl
    - email
    - phone (or: mobile, telephone)
    - address
    - city
    - region
    - is_boarder (or: boarder) - values: Yes/No, True/False, 1/0

    Returns preview data in preview mode, or import results in import mode.
    """
    # Validate file type
    content_type = file.content_type or ""
    if content_type not in ALLOWED_IMPORT_TYPES:
        # Try to detect from filename
        filename = file.filename or ""
        if filename.lower().endswith(".csv"):
            file_type = "csv"
        elif filename.lower().endswith(".xlsx"):
            file_type = "xlsx"
        elif filename.lower().endswith(".xls"):
            file_type = "xls"
        else:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Invalid file type. Allowed: CSV, XLS, XLSX. Got: {content_type}",
            )
    else:
        file_type = ALLOWED_IMPORT_TYPES[content_type]

    # Read file content
    content = await file.read()

    # Validate file size
    if len(content) > MAX_IMPORT_SIZE:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"File too large. Maximum size is 5MB. Got: {len(content) / 1024 / 1024:.2f}MB",
        )

    # Validate file is not empty
    if len(content) == 0:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="File is empty",
        )

    # Import students
    service = StudentService(db)
    try:
        result = await service.import_students_from_file(
            tenant_id=tenant.tenant_id,
            file_content=content,
            file_type=file_type,
            preview_only=preview,
            auto_generate_ids=auto_generate_ids,
        )
        return StudentImportResponse(**result)
    except StudentServiceError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=e.message,
        )


@router.get(
    "/import/template",
    summary="Download import template",
    description="Get a CSV template for student import.",
)
async def get_import_template() -> dict:
    """
    Return the CSV template headers for student import.

    Use this to create a properly formatted import file.

    Note: The system always auto-generates a unique student ID (e.g., STU-2026-001).
    Use the previous_student_id column to preserve IDs from previous/external systems.
    """
    return {
        "headers": [
            "previous_student_id",
            "first_name",
            "middle_name",
            "last_name",
            "date_of_birth",
            "gender",
            "email",
            "phone",
            "address",
            "city",
            "region",
            "is_boarder",
        ],
        "example_row": {
            "previous_student_id": "OLD-SYS-001",
            "first_name": "Kofi",
            "middle_name": "Mensah",
            "last_name": "Asante",
            "date_of_birth": "2010-05-15",
            "gender": "male",
            "email": "kofi.asante@example.com",
            "phone": "+233244123456",
            "address": "123 Independence Ave",
            "city": "Accra",
            "region": "Greater Accra",
            "is_boarder": "no",
        },
        "notes": [
            "previous_student_id: Optional - ID from previous/external system for reference",
            "student_id: Auto-generated by system (e.g., STU-2026-001) - not in template",
            "date_of_birth: Supports formats like YYYY-MM-DD, DD/MM/YYYY",
            "gender: Accepts M/F, Male/Female, Boy/Girl",
            "is_boarder: Accepts Yes/No, True/False, 1/0",
        ],
    }


# =========================
# Guardian Endpoints
# =========================


@router.post(
    "/{student_id}/guardians",
    response_model=StudentGuardianResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Add guardian to student",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def add_guardian_to_student(
    student_id: UUID,
    data: StudentGuardianWithNewGuardian,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentGuardianResponse:
    """Create a new guardian and link to student."""
    service = StudentService(db)
    try:
        # First create the guardian
        guardian = await service.create_guardian(
            tenant_id=tenant.tenant_id,
            **data.guardian.model_dump(),
        )

        # Then link to student
        link = await service.link_guardian_to_student(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            guardian_id=guardian.id,
            relationship=data.relationship,
            is_primary=data.is_primary,
            is_emergency_contact=data.is_emergency_contact,
            can_pickup=data.can_pickup,
        )

        return StudentGuardianResponse(
            id=link.id,
            student_id=link.student_id,
            guardian_id=link.guardian_id,
            relationship=link.relation_type.value,
            is_primary=link.is_primary,
            is_emergency_contact=link.is_emergency_contact,
            can_pickup=link.can_pickup,
            guardian=GuardianResponse.model_validate(guardian),
            created_at=link.created_at,
            updated_at=link.updated_at,
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.post(
    "/{student_id}/guardians/link",
    response_model=StudentGuardianResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Link existing guardian to student",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def link_existing_guardian(
    student_id: UUID,
    data: StudentGuardianCreate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentGuardianResponse:
    """Link an existing guardian to a student."""
    service = StudentService(db)
    try:
        link = await service.link_guardian_to_student(
            tenant_id=tenant.tenant_id,
            student_id=student_id,
            guardian_id=data.guardian_id,
            relationship=data.relationship,
            is_primary=data.is_primary,
            is_emergency_contact=data.is_emergency_contact,
            can_pickup=data.can_pickup,
        )

        guardian = await service.get_guardian(tenant.tenant_id, data.guardian_id)

        return StudentGuardianResponse(
            id=link.id,
            student_id=link.student_id,
            guardian_id=link.guardian_id,
            relationship=link.relation_type.value,
            is_primary=link.is_primary,
            is_emergency_contact=link.is_emergency_contact,
            can_pickup=link.can_pickup,
            guardian=GuardianResponse.model_validate(guardian),
            created_at=link.created_at,
            updated_at=link.updated_at,
        )
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@router.get(
    "/{student_id}/guardians",
    response_model=list[StudentGuardianResponse],
    summary="Get student's guardians",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_student_guardians(
    student_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> list[StudentGuardianResponse]:
    """Get all guardians linked to a student."""
    service = StudentService(db)
    links = await service.get_student_guardians(tenant.tenant_id, student_id)

    return [
        StudentGuardianResponse(
            id=link.id,
            student_id=link.student_id,
            guardian_id=link.guardian_id,
            relationship=link.relation_type.value,
            is_primary=link.is_primary,
            is_emergency_contact=link.is_emergency_contact,
            can_pickup=link.can_pickup,
            guardian=GuardianResponse.model_validate(link.guardian_rel),
            created_at=link.created_at,
            updated_at=link.updated_at,
        )
        for link in links
    ]


@router.put(
    "/{student_id}/guardians/{guardian_id}",
    response_model=StudentGuardianResponse,
    summary="Update guardian link",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def update_guardian_link(
    student_id: UUID,
    guardian_id: UUID,
    data: StudentGuardianUpdate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> StudentGuardianResponse:
    """Update a student-guardian link."""
    service = StudentService(db)

    # Find the link first
    links = await service.get_student_guardians(tenant.tenant_id, student_id)
    link = next((l for l in links if l.guardian_id == guardian_id), None)

    if not link:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Guardian link not found",
        )

    updated_link = await service.update_student_guardian_link(
        link_id=link.id,
        tenant_id=tenant.tenant_id,
        student_id=student_id,
        **data.model_dump(exclude_unset=True),
    )

    guardian = await service.get_guardian(tenant.tenant_id, guardian_id)

    return StudentGuardianResponse(
        id=updated_link.id,
        student_id=updated_link.student_id,
        guardian_id=updated_link.guardian_id,
        relationship=updated_link.relation_type.value,
        is_primary=updated_link.is_primary,
        is_emergency_contact=updated_link.is_emergency_contact,
        can_pickup=updated_link.can_pickup,
        guardian=GuardianResponse.model_validate(guardian),
        created_at=updated_link.created_at,
        updated_at=updated_link.updated_at,
    )


@router.delete(
    "/{student_id}/guardians/{guardian_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Unlink guardian from student",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def unlink_guardian(
    student_id: UUID,
    guardian_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> None:
    """Remove a guardian link from a student."""
    service = StudentService(db)
    unlinked = await service.unlink_guardian_from_student(tenant.tenant_id, student_id, guardian_id)

    if not unlinked:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Guardian link not found",
        )


# =========================
# Standalone Guardian Endpoints
# =========================


guardians_router = APIRouter()


@guardians_router.post(
    "",
    response_model=GuardianResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create guardian",
    dependencies=[Depends(require_permissions("students.create"))],
)
async def create_guardian(
    data: GuardianCreate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> GuardianResponse:
    """Create a new guardian (without linking to a student)."""
    service = StudentService(db)
    try:
        guardian = await service.create_guardian(
            tenant_id=tenant.tenant_id,
            **data.model_dump(),
        )
        return GuardianResponse.model_validate(guardian)
    except StudentServiceError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=e.message)


@guardians_router.get(
    "",
    response_model=dict,
    summary="List guardians",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def list_guardians(
    tenant: RequestTenant,
    db: DatabaseSession,
    search: Optional[str] = Query(None, description="Search by name, phone, or email"),
    page: int = Query(1, ge=1, description="Page number"),
    page_size: int = Query(20, ge=1, le=100, description="Items per page"),
) -> dict:
    """List guardians with pagination and student counts."""
    service = StudentService(db)
    guardians, total = await service.list_guardians(
        tenant_id=tenant.tenant_id,
        search=search,
        page=page,
        page_size=page_size,
    )

    total_pages = (total + page_size - 1) // page_size if total > 0 else 0

    return {
        "items": guardians,  # Already contains student_count
        "total": total,
        "page": page,
        "page_size": page_size,
        "total_pages": total_pages,
        "has_next": page < total_pages,
        "has_previous": page > 1,
    }


@guardians_router.get(
    "/{guardian_id}",
    response_model=GuardianResponse,
    summary="Get guardian details",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_guardian(
    guardian_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> GuardianResponse:
    """Get guardian by ID."""
    service = StudentService(db)
    guardian = await service.get_guardian(tenant.tenant_id, guardian_id)

    if not guardian:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Guardian not found",
        )

    return GuardianResponse.model_validate(guardian)


@guardians_router.put(
    "/{guardian_id}",
    response_model=GuardianResponse,
    summary="Update guardian",
    dependencies=[Depends(require_permissions("students.update"))],
)
async def update_guardian(
    guardian_id: UUID,
    data: GuardianUpdate,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> GuardianResponse:
    """Update a guardian."""
    service = StudentService(db)
    guardian = await service.update_guardian(
        tenant_id=tenant.tenant_id,
        guardian_id=guardian_id,
        **data.model_dump(exclude_unset=True),
    )

    if not guardian:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Guardian not found",
        )

    return GuardianResponse.model_validate(guardian)


@guardians_router.delete(
    "/{guardian_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete guardian",
    dependencies=[Depends(require_permissions("students.delete"))],
)
async def delete_guardian(
    guardian_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> None:
    """Soft delete a guardian."""
    service = StudentService(db)
    try:
        deleted = await service.delete_guardian(tenant.tenant_id, guardian_id)

        if not deleted:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Guardian not found",
            )
    except StudentServiceError as e:
        if e.code == "guardian_has_linked_students":
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=str(e),
            )
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )


@guardians_router.get(
    "/{guardian_id}/students",
    response_model=list[StudentListResponse],
    summary="Get guardian's students",
    dependencies=[Depends(require_permissions("students.read"))],
)
async def get_guardian_students(
    guardian_id: UUID,
    tenant: RequestTenant,
    db: DatabaseSession,
) -> list[StudentListResponse]:
    """Get all students linked to a guardian."""
    service = StudentService(db)
    links = await service.get_guardian_students(tenant.tenant_id, guardian_id)

    return [
        StudentListResponse(
            id=link.student_rel.id,
            student_id=link.student_rel.student_id,
            previous_student_id=link.student_rel.previous_student_id,
            first_name=link.student_rel.first_name,
            middle_name=link.student_rel.middle_name,
            last_name=link.student_rel.last_name,
            gender=link.student_rel.gender.value,
            date_of_birth=link.student_rel.date_of_birth,
            status=link.student_rel.status.value,
            class_id=link.student_rel.class_id,
            class_name=link.student_rel.class_.name if link.student_rel.class_ else None,
            section_id=link.student_rel.section_id,
            section_name=link.student_rel.section.name if link.student_rel.section else None,
            photo_url=link.student_rel.photo_url,
        )
        for link in links
    ]
